CREATE TABLE Tags.Target
(
    TargetKey INT NOT NULL IDENTITY
        CONSTRAINT PK_Target PRIMARY KEY,
    TargetName NVARCHAR(50) NOT NULL
        CONSTRAINT UK_Measure_TargetName
        UNIQUE,
    SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME(SysStartTime, SysEndTime)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = Tags.Target_History) );
GO
GRANT SELECT, INSERT, UPDATE  ON Tags.Target TO HemaWeb;