CREATE TABLE dbo.AspNetRoles
(
    Id NVARCHAR(450) NOT NULL,
    ConcurrencyStamp NVARCHAR(MAX) NULL,
    Name NVARCHAR(256) NULL,
    NormalizedName NVARCHAR(256) NULL,
    CONSTRAINT PK_AspNetRoles
        PRIMARY KEY CLUSTERED (Id ASC),
    SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME(SysStartTime, SysEndTime)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.AspNetRoles_History));


GO
CREATE NONCLUSTERED INDEX RoleNameIndex
ON dbo.AspNetRoles (NormalizedName ASC);

